Repository parameter1/pmmi-media-group-websites, pull requests merged in 2022-09, with the labels that each got.

#447 Fix company address block
  packages/global/components/layouts/content/company.marko
Labels: 🌐 site: ALL

#444 Additional translation support, Mundo
  packages/global/components/blocks/native-x-list.marko
  packages/global/components/layouts/website-section/feed.marko
  packages/global/package.json
  packages/theme-monorail-leaders/package.json
  sites/automationworld.com/package.json
  sites/healthcarepackaging.com/package.json
  sites/mundopmmi.com/config/i18n.js
  sites/mundopmmi.com/package.json
  sites/mundopmmi.com/server/styles/index.scss
  sites/mundopmmi.com/server/templates/index.marko
  sites/oemmagazine.org/package.json
  sites/packworld.com/package.json
  sites/profoodworld.com/package.json
  yarn.lock
Labels: 🌐 site: mundopmmi.com

#446 Enable Inquiry on all content pages regardless of content type.
  packages/global/components/layouts/content/default.marko
  packages/theme-monorail-leaders/graphql/fragment-factories/content-page.js
Labels: 🌐 site: ALL

#450 Upgrade dependencies
  packages/global/package.json
  packages/theme-monorail-leaders/package.json
  sites/automationworld.com/package.json
  sites/healthcarepackaging.com/package.json
  sites/mundopmmi.com/package.json
  sites/oemmagazine.org/package.json
  sites/packworld.com/package.json
  sites/profoodworld.com/package.json
  yarn.lock
Labels: 🌐 site: ALL

#451 Upgrade dependencies
  packages/global/package.json
  packages/theme-monorail-leaders/package.json
  sites/automationworld.com/package.json
  sites/healthcarepackaging.com/package.json
  sites/mundopmmi.com/package.json
  sites/oemmagazine.org/package.json
  sites/packworld.com/package.json
  sites/profoodworld.com/package.json
  yarn.lock
Labels: 🌐 site: ALL

#452 Adjust position of company block for demo
  packages/global/components/layouts/content/default.marko
  packages/global/components/leaders/contextual.marko
  packages/global/scss/core.scss
Labels: 🌐 site: ALL

#453 Presented by -> Sponsored by, PFW Global 250.
  sites/profoodworld.com/server/templates/website-section/global-250.marko
Labels: 🌐 site: profoodworld

#455 Remove demo
  packages/global/components/layouts/content/default.marko
Labels: 🌐 site: ALL

#456 Remove demo expansion values
  packages/global/components/leaders/contextual.marko
Labels: 🌐 site: ALL
